spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ucnnct
          jwk-set-uri: http://localhost:8081/realms/ucnnct/protocol/openid-connect/certs

hello:
  message: ${HELLO_MESSAGE:Hello from auth-service}

server:
  port: 8090

logging:
  level:
    org.springframework.security: DEBUG
    root: INFO
