server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location ~ ^/(dev|staging)(/|$) {
    rewrite ^/(dev|staging)(/|$)(.*)$ /$3 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
