package cc.uconnect.enums;

public enum WsOutboundActionType {
    PRIVATE_MESSAGE,
    GROUP_MESSAGE,
    FILE_MESSAGE,
    NOTIFICATION,
    MESSAGE_SENT_ACK,
    GROUP_MESSAGE_SENT_ACK,
    FILE_MESSAGE_SENT_ACK,
    MESSAGE_READ_CONFIRMED,
    GROUP_MESSAGE_READ_CONFIRMED,
    UPLOAD_COMPLETED_ACK,
    DOWNLOAD_REQUEST_ACK,
    ERROR
}
