spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/chatdb}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: chat-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "cc.uconnect.kafka.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWKSET_URI:http://localhost:8882/realms/ucnnct/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8882/realms/ucnnct}

server:
  port: 8084
