package cc.uconnect.enums;

public enum NotificationCategory {
    PRIVATE_MESSAGE_IN_APP,
    GROUP_MESSAGE_IN_APP,
    GROUP_MEMBER_ADDED_IN_APP,
    GROUP_DELETED_IN_APP,
    FRIEND_REQUEST_IN_APP,
    FRIEND_REQUEST_ACCEPTED_IN_APP,
    FRIEND_REQUEST_REJECTED_IN_APP,
    FRIEND_REMOVED_IN_APP
}
